### ISSUE TITLE
TypeError: save_checkpoint_solution_h5() takes 7 positional arguments but 8 were given

### ISSUE THREAD

**Issue by lshahid** [KVSlab/OasisMove#25]
Hello,

I tried to run the default `oasism NSfracStepMove` command inside your Docker container. It runs for about 400 timesteps, but then stops. This is the following error message I get:

<img width="1059" alt="Screen Shot 2023-12-08 at 10 31 49 AM" src="https://github.com/KVSlab/OasisMove/assets/55703996/1f26c492-7558-45f6-b32a-cc4e3c490a27">

I verified that OasisMove was installed correctly in the container. How can I solve this problem?

Thanks,
Labib

**Comment by hkjeldsberg** [comment]
@lshahid Dear Labib,

Apologies for the late reply, and thanks for reporting this issue! This made me realise that the docker version of OasisMove was heavily outdated. In this regard I have made a new release (`oasismove v.0.3.0`), with changes that should fix the issue you experienced. 

You can download it through:
```
docker pull ghcr.io/kvslab/oasismove:v0.3.0
```

Note that the run command is now `oasismove`: 
```
oasismove NSfracStepMove
```

instead of `oasism`. 
I hope this resolves your issue! 

Regards,
Henrik

**Comment by lshahid** [comment]
Thanks, Henrik, for the quick fix to the Docker container! I ran the `oasismove NSfracStepMove` command in a new container and the Driven Cavity problem ran as expected. I visualized the results, and they look correct. At the end of the simulation, the following error message was shown:

![Screen Shot 2023-12-11 at 11 37 49 PM](https://github.com/KVSlab/OasisMove/assets/55703996/ba87e859-d487-430c-aab8-84c86ae31f1e)

I don't think it is a fatal error since the simulations results look correct. But I just thought I should let you know.

Best,
Labib
